# fly.toml app configuration file generated for betalyr-learning-server on 2025-04-20T19:56:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'betalyr-learning-server'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  GIN_MODE = 'release'
  APP_ENV = 'production'
  APP_VERSION = '1.0.0'
  DB_HOST = 'postgres'
  DB_PORT = '5432'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/status'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
