# fly.toml app configuration file generated for betalyr-learning-server on 2025-04-20T19:56:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'betalyr-learning-server'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  GIN_MODE = 'release'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
