version: '3.8'

services:
  app:
    image: golang:1.21-bullseye
    volumes:
      - ..:/workspace
      # 避免Go模块缓存重复下载
      - go-mod:/go/pkg/mod 
    working_dir: /workspace
    environment:
      - GOPATH=/go
    # 开发容器保持常驻
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: betalyr_lerning_dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: betalyr_lerningdb_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  go-mod:
  pgdata:
  redisdata: