db:
  host: ${DB_HOST:-}
  port: ${DB_PORT:-}
  user: ${DB_USER:-}
  password: ${DB_PASSWORD:-}
  dbname: ${DB_NAME:-}

server:
  port: ${SERVER_PORT:-8000} 
  
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:-}
  api_key: ${CLOUDINARY_API_KEY:-}
  api_secret: ${CLOUDINARY_API_SECRET:-} 